/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package deliveryapp;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author djaco
 */
public class RepartidorScreen extends javax.swing.JPanel {

    Metodos generar = new Metodos();
    public RepartidorScreen() {
        initComponents();
        nameLbl.setVisible(false);
        nameField.setVisible(false);
        vehicleLbl.setVisible(false);
        vehicleBox.setVisible(false);
        registerBtn.setVisible(false);
        scrollPane.setVisible(false);
        listaTxtArea.setVisible(false);
        //reloadBtn.setVisible(false);
        delBtn.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        delBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        listarBtn = new javax.swing.JButton();
        nameLbl = new javax.swing.JLabel();
        vehicleLbl = new javax.swing.JLabel();
        vehicleBox = new javax.swing.JComboBox<>();
        registerBtn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        listaTxtArea = new javax.swing.JTextArea();
        nameField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(19, 28, 38));

        delBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/deleteBtn.png"))); // NOI18N
        delBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delBtnActionPerformed(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(31, 114, 193));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Agregar Repartidor");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(31, 114, 193));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Buscar Repartidor");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        listarBtn.setBackground(new java.awt.Color(31, 114, 193));
        listarBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listarBtn.setForeground(new java.awt.Color(255, 255, 255));
        listarBtn.setText("Listar Repartidores");
        listarBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarBtnActionPerformed(evt);
            }
        });

        nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameLbl.setText("NOMBRE:");

        vehicleLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleLbl.setForeground(new java.awt.Color(255, 255, 255));
        vehicleLbl.setText("VEHICULO:");

        vehicleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Carro", "Moto", "Bicicleta", "Camion" }));

        registerBtn.setBackground(new java.awt.Color(31, 114, 193));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Registrar");
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        listaTxtArea.setBackground(new java.awt.Color(19, 28, 38));
        listaTxtArea.setColumns(20);
        listaTxtArea.setForeground(new java.awt.Color(255, 255, 255));
        listaTxtArea.setRows(5);
        listaTxtArea.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPARTIDORES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        scrollPane.setViewportView(listaTxtArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleLbl, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(vehicleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(registerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(157, 157, 157)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(addBtn)
                            .addGap(32, 32, 32)
                            .addComponent(searchBtn)
                            .addGap(33, 33, 33)
                            .addComponent(listarBtn))))
                .addContainerGap(141, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(searchBtn)
                    .addComponent(listarBtn))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(registerBtn)
                    .addComponent(vehicleLbl))
                .addGap(42, 42, 42)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        nameLbl.setVisible(true);
        nameField.setVisible(true);
        vehicleLbl.setVisible(true);
        vehicleBox.setVisible(true);
        registerBtn.setVisible(true);
        scrollPane.setVisible(false);
        listaTxtArea.setVisible(false);
        //reloadBtn.setVisible(false);
        delBtn.setVisible(false);
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        nameLbl.setVisible(false);
        nameField.setVisible(false);
        vehicleLbl.setVisible(false);
        vehicleBox.setVisible(false);
        registerBtn.setVisible(false);
        scrollPane.setVisible(false);
        listaTxtArea.setVisible(false);
        //reloadBtn.setVisible(false);
        delBtn.setVisible(false);
        
        if (Dashboard.repartidores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todavia no hay repartidores registrados", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            String resultado = "";
            String busqueda = JOptionPane.showInputDialog(this, "Ingrese dato a buscar:");
            for (int i = 0; i < Dashboard.repartidores.size(); i++) {
                Repartidor buscarR = Dashboard.repartidores.get(i);
                if (buscarR.getNombre().equalsIgnoreCase(busqueda) || buscarR.getIdRepartidor().equals(busqueda) || buscarR.getVehiculo().equalsIgnoreCase(busqueda)) {
                    resultado += buscarR + "\n";
                }
            }
            
            if (resultado.equals("")) {
                JOptionPane.showMessageDialog(this, "No se obtuvieron resultados de la busqueda", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, resultado, "RESULTADO", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void listarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarBtnActionPerformed
        String lista = "";
        if (Dashboard.repartidores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Todavia no hay repartidores registrados", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            nameLbl.setVisible(false);
            nameField.setVisible(false);
            vehicleLbl.setVisible(false);
            vehicleBox.setVisible(false);
            registerBtn.setVisible(false);
            int indice = 0;
            for (int i = 0; i < Dashboard.repartidores.size(); i++) {
                Repartidor listado = Dashboard.repartidores.get(i);
                indice++;
                lista += indice + ") " + listado + "\n"; 
            }
            listaTxtArea.setText(lista);
            scrollPane.setVisible(true);
            listaTxtArea.setVisible(true);
            listaTxtArea.setEditable(false);
            //reloadBtn.setVisible(true);
            delBtn.setVisible(true);
        }
    }//GEN-LAST:event_listarBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        String nombre = nameField.getText();
        String id = generar.generarId(nombre);
        String vehiculo = vehicleBox.getSelectedItem().toString();
        
        boolean esCorrecto = true;
        
        if (nombre.isEmpty() || nombre.isBlank()) {
            JOptionPane.showMessageDialog(this, "Nombre vacio", "WARNING", JOptionPane.WARNING_MESSAGE);
            esCorrecto = false;
        } else if (vehiculo.equals(" ")) {
            JOptionPane.showMessageDialog(this, "No has seleccionado un vehiculo para el repartidor", "WARNING", JOptionPane.WARNING_MESSAGE);
            esCorrecto = false;
        }
        
        if(!esCorrecto) {
            JOptionPane.showMessageDialog(this, "No se agrego el repartidor", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            Repartidor repartidor = new Repartidor(nombre, id, vehiculo);
            Dashboard.repartidores.add(repartidor);
            JOptionPane.showMessageDialog(this, "Se agrego el repartidor con exito", "EXITO", JOptionPane.INFORMATION_MESSAGE);
        }
        
        nameField.setText(null);
        vehicleBox.setSelectedItem(" ");
    }//GEN-LAST:event_registerBtnActionPerformed

    private void delBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delBtnActionPerformed
        if (Dashboard.repartidores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay repartidores registrados", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            String borrarR = JOptionPane.showInputDialog(this, "Ingrese dato del repartidor a borrar");
            boolean borrado = false;
            for (int i = 0; i < Dashboard.repartidores.size(); i++) {
                Repartidor repartidorBorrar = Dashboard.repartidores.get(i);
                if (repartidorBorrar.getNombre().equalsIgnoreCase(borrarR) || repartidorBorrar.getIdRepartidor().equals(borrarR)) {
                    Dashboard.repartidores.remove(repartidorBorrar);
                    borrado = true;
                    break;
                }
            }
            
            if (!borrado) {
                JOptionPane.showMessageDialog(this, "No se elimino el repartidor", "ERROR", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Se borro el repartidor con exito", "EXITO", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_delBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton delBtn;
    private javax.swing.JTextArea listaTxtArea;
    private javax.swing.JButton listarBtn;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton registerBtn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton searchBtn;
    private javax.swing.JComboBox<String> vehicleBox;
    private javax.swing.JLabel vehicleLbl;
    // End of variables declaration//GEN-END:variables
}
