/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package deliveryapp;

import javax.swing.JOptionPane;


public class ScreenRepartidor extends javax.swing.JPanel {

    Metodos mt = new Metodos();
    
    public ScreenRepartidor() {
        initComponents();
        nameLbl.setVisible(false);
        nameField.setVisible(false);
        vehicleLbl.setVisible(false);
        vehicleBox.setVisible(false);
        registerBtn.setVisible(false);
        scrollPane.setVisible(false);
        listaRepartidores.setVisible(false);
        updateLista.setVisible(false);
        updateRepartidor.setVisible(false);
        deleteRepartidor.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addBtn = new javax.swing.JButton();
        searchBtn = new javax.swing.JButton();
        listBtn = new javax.swing.JButton();
        nameField = new javax.swing.JTextField();
        vehicleBox = new javax.swing.JComboBox<>();
        nameLbl = new javax.swing.JLabel();
        vehicleLbl = new javax.swing.JLabel();
        registerBtn = new javax.swing.JButton();
        scrollPane = new javax.swing.JScrollPane();
        listaRepartidores = new javax.swing.JTextArea();
        updateLista = new javax.swing.JButton();
        updateRepartidor = new javax.swing.JButton();
        deleteRepartidor = new javax.swing.JButton();

        setBackground(new java.awt.Color(19, 28, 38));
        setMaximumSize(new java.awt.Dimension(766, 488));
        setMinimumSize(new java.awt.Dimension(766, 488));

        addBtn.setBackground(new java.awt.Color(31, 114, 193));
        addBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Agregar Repartidor");
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(31, 114, 193));
        searchBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Buscar Repartidor");
        searchBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        listBtn.setBackground(new java.awt.Color(31, 114, 193));
        listBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        listBtn.setForeground(new java.awt.Color(255, 255, 255));
        listBtn.setText("Listar Repartidores");
        listBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        listBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listBtnActionPerformed(evt);
            }
        });

        vehicleBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Carro", "Bicicleta", "Moto", "Camion" }));
        vehicleBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleBoxActionPerformed(evt);
            }
        });

        nameLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        nameLbl.setForeground(new java.awt.Color(255, 255, 255));
        nameLbl.setText("Nombre:");

        vehicleLbl.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        vehicleLbl.setForeground(new java.awt.Color(255, 255, 255));
        vehicleLbl.setText("Vehiculo:");

        registerBtn.setBackground(new java.awt.Color(31, 114, 193));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(255, 255, 255));
        registerBtn.setText("Registrar");
        registerBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerBtnActionPerformed(evt);
            }
        });

        listaRepartidores.setEditable(false);
        listaRepartidores.setBackground(new java.awt.Color(19, 28, 38));
        listaRepartidores.setColumns(20);
        listaRepartidores.setForeground(new java.awt.Color(255, 255, 255));
        listaRepartidores.setRows(5);
        listaRepartidores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REPARTIDORES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        scrollPane.setViewportView(listaRepartidores);

        updateLista.setBackground(new java.awt.Color(31, 114, 193));
        updateLista.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateLista.setForeground(new java.awt.Color(255, 255, 255));
        updateLista.setText("Actualizar");
        updateLista.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateListaActionPerformed(evt);
            }
        });

        updateRepartidor.setBackground(new java.awt.Color(31, 114, 193));
        updateRepartidor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        updateRepartidor.setForeground(new java.awt.Color(255, 255, 255));
        updateRepartidor.setText("Actualizar Repartidor");
        updateRepartidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        updateRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateRepartidorActionPerformed(evt);
            }
        });

        deleteRepartidor.setBackground(new java.awt.Color(255, 51, 51));
        deleteRepartidor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteRepartidor.setForeground(new java.awt.Color(255, 255, 255));
        deleteRepartidor.setText("Borrar Repartidor");
        deleteRepartidor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteRepartidor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteRepartidorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vehicleLbl)
                            .addComponent(nameLbl))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(vehicleBox, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(registerBtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(listBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(updateLista)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(updateRepartidor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(deleteRepartidor))
                            .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(123, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn)
                    .addComponent(searchBtn)
                    .addComponent(listBtn))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(vehicleBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vehicleLbl)
                    .addComponent(registerBtn))
                .addGap(34, 34, 34)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updateLista)
                    .addComponent(updateRepartidor)
                    .addComponent(deleteRepartidor))
                .addContainerGap(34, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        nameLbl.setVisible(true);
        nameField.setVisible(true);
        vehicleLbl.setVisible(true);
        vehicleBox.setVisible(true);
        registerBtn.setVisible(true);
    }//GEN-LAST:event_addBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        nameLbl.setVisible(false);
        nameField.setVisible(false);
        vehicleLbl.setVisible(false);
        vehicleBox.setVisible(false);
        registerBtn.setVisible(false);
        scrollPane.setVisible(false);
        listaRepartidores.setVisible(false);
        updateLista.setVisible(false);
        updateRepartidor.setVisible(false);
        deleteRepartidor.setVisible(false);
        
        if (Dashboard.repartidores.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No hay repartidores registrados", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            String search = JOptionPane.showInputDialog(this, "Ingrese parametros de busqueda");
            if (search == null || search.isBlank()) {
                return;
            }
            
            String resultado = "";
            
            for(Repartidor repartidor : Dashboard.repartidores) {
                if(repartidor.getNombre().equalsIgnoreCase(search) || repartidor.getIdRepartidor().equals(search) || repartidor.getVehiculo().equalsIgnoreCase(search)) {
                    resultado += repartidor +"\n";
                }
            }
            
            if(resultado.equals("")) {
                JOptionPane.showMessageDialog(this, "No se obtuvieron resultados", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Resultados encontrados!\n" + resultado, "ENCONTRADO", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void listBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_listBtnActionPerformed

    private void registerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerBtnActionPerformed
        boolean agregado = true;
        String name = nameField.getText();
        String vehiculo = "";
        String seleccion = vehicleBox.getSelectedItem().toString();
        
        if(name.isEmpty() || name.isBlank()) {
            agregado = false;
            JOptionPane.showMessageDialog(this, "Nombre vacio", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        }
        
        if (seleccion.equals(" ")) {
            agregado = false;
            JOptionPane.showMessageDialog(this, "No elegiste un vehiculo", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
        } else {
            vehiculo = seleccion;
        }
        
        if (!agregado) {
            JOptionPane.showMessageDialog(this, "No se agrego el repartidor dado", "ERROR", JOptionPane.ERROR_MESSAGE);
        } else {
            String idRepartidor = mt.generarId(name);
            Repartidor newRepartidor = new Repartidor(name, idRepartidor, vehiculo);
            Dashboard.repartidores.add(newRepartidor);
            JOptionPane.showMessageDialog(this, "Repartidor agregado con exito", "EXITO", JOptionPane.INFORMATION_MESSAGE);
        }
        
        nameField.setText(null);
        vehicleBox.setSelectedItem(" ");
        
        
    }//GEN-LAST:event_registerBtnActionPerformed

    private void updateListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateListaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateListaActionPerformed

    private void updateRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateRepartidorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateRepartidorActionPerformed

    private void deleteRepartidorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteRepartidorActionPerformed
        

    }//GEN-LAST:event_deleteRepartidorActionPerformed

    private void vehicleBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleBoxActionPerformed

    }//GEN-LAST:event_vehicleBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton deleteRepartidor;
    private javax.swing.JButton listBtn;
    private javax.swing.JTextArea listaRepartidores;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JButton registerBtn;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateLista;
    private javax.swing.JButton updateRepartidor;
    private javax.swing.JComboBox<String> vehicleBox;
    private javax.swing.JLabel vehicleLbl;
    // End of variables declaration//GEN-END:variables
}
